// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ApmVSExtension
{
	internal sealed partial class Vsix
	{
		public const string Id = "ApmVSExtension.380f2479-672a-4a02-b2b4-0ebfe3e8d428";
		public const string Name = "ApmVSExtension";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "Vestas Wind Systems A/S";
		public const string Tags = "";
	}
}
