// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ApmVSExtension
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ApmVSExtensionString = "ff3b2bf5-536d-4b04-8f7a-d48ac2a08c2d";
        public static Guid ApmVSExtension = new Guid(ApmVSExtensionString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SolutionExplorerGroup = 0x1020;
        public const int SolutionNodeMenuGroup = 0x0001;
        public const int ProjectNodeMenuGroup = 0x0002;
        public const int CreateAgentPackageCommand = 0x0100;
        public const int CreateProjectAgentPackageCommand = 0x0101;
    }
}
